backend:
  name: github
  repo: IstamovVv/bum43
  branch: main
  client_id: Ov23liDhelZ1lDAWzp2Q

# Папка для загружаемых изображений
media_folder: "public/images/uploads"
# Путь к картинкам на сайте (с учётом baseURL)
public_folder: "/bum43/images/uploads"

# Коллекция: Категории
collections:
  - name: "categories"
    label: "Категории"
    folder: "content/categories"
    create: true
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Слаг (URL)", name: "slug", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }

  # Коллекция: Товары
  - name: "products"
    label: "Товары"
    folder: "content/products"
    create: true
    fields:
      - { label: "Название товара", name: "title", widget: "string" }
      - { label: "Категория", name: "category", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "slug" }
      - { label: "Цена", name: "price", widget: "number" }
      - { label: "Изображение", name: "image", widget: "image" }
      - { label: "Описание", name: "body", widget: "markdown" }